on:
  push:
    branches: ["**"]
  # Allows to trigger the workflow manually

jobs:
  TestGeokitDevLocal:
    name: numba=${{ matrix.numba_version }} os=${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        # os: ["ubuntu-latest"]
        numba_version:
          [ 0.65.0,  0.64.0,0.63.1,0.63.0,0.62.1,0.62.0,0.61.2,0.61.0,0.60.0,0.59.1,0.59.0,0.58.1,0.57.1,0.57.0,0.56.4,0.56.3,0.56.2,0.55.2,0.55.1,0.55.0,0.54.1,0.54.0,0.53.1,0.53.0,0.52.0,0.51.2,0.51.1,0.51.0,0.50.1,0.49.1,0.49.0,0.48.0,0.47.0,0.46.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          activate-environment: reskit_env
          conda-remove-defaults: true
      - name: Run tests
        shell: pwsh
        run: |
          ls
          echo "LS Done"
          mamba create --name test_env numba=${{ matrix.numba_version }} 
          echo "Installation done"
          mamba list --name test_env
          echo "libaries printed"
          echo "start pytest"
          mamba run --name test_env python test_script.py