on:
  push:
    branches: ["**"]
  # Allows to trigger the workflow manually

jobs:
  TestGeokitDevLocal:
    name: numba=${{ matrix.numba_version }} os=${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        # os: ["ubuntu-latest"]
        numba_version:
          [0.55.2, 0.55.1, 0.55.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          activate-environment: reskit_env
          conda-remove-defaults: true
      - name: Run tests
        shell: pwsh
        run: |
          ls
          echo "LS Done"
          mamba create --name test_env numba=${{ matrix.numba_version }} "setuptools<82"
          echo "Installation done"
          mamba list --name test_env
          echo "libaries printed"
          echo "start pytest"
          mamba run --name test_env python test_script.py